### ISSUE TITLE
TypeError: Cannot read property 'getQueryInterface' of undefined  at Function.get queryInterface

### ISSUE THREAD

**Issue by aguileraq** [Duomly/nodejs-backend-bankapp#1]
i got this error when i type in the terminal the command: npm run migrate up

The sequelize version in my project:  "^6.2.4"

**Comment by radoslawfabisiak** [comment]
Hello, if you change the version of dependencies is kinda often your project will not work.

Please, clone our repository, make sure, your connection with the database is correct, and try.
